{{- if .Values.loadDemoData -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "atlas.fullname" . }}-{{ randAlphaNum 5 | lower }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: {{ include "atlas.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "python", "manage.py", "loaddata", "data/demo.json" ]
          envFrom:
            - secretRef:
                name: {{ include "atlas.fullname" . }}
      restartPolicy: Never
{{- end }}
